version: '3.4'

services:
  sql-server-db:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server:2017-latest
    ports:
      - "1433:1433"
    volumes:
      - C:\dockervolumes\eventsourcing:/var/opt/mssql/data 
    environment:
      SA_PASSWORD: "1Tp1TBD46"
      ACCEPT_EULA: "Y"